"""Remove age_range from modules

Revision ID: 8474ddf7eac5
Revises: 90a4fc422c59
Create Date: 2026-08-04 17:08:26.048525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8474ddf7eac5'
down_revision: Union[str, None] = '90a4fc422c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'age_range')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('age_range', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
