"""Remove duration and price fields from modules

Revision ID: c69203524496
Revises: 8474ddf7eac5
Create Date: 2026-08-04 17:15:45.133285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69203524496'
down_revision: Union[str, None] = '8474ddf7eac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'price_on_one')
    op.drop_column('modules', 'price_group')
    op.drop_column('modules', 'duration_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('duration_minutes', sa.INTEGER(), nullable=False))
    op.add_column('modules', sa.Column('price_group', sa.FLOAT(), nullable=False))
    op.add_column('modules', sa.Column('price_on_one', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###
